"""
Discriminator module — evaluates the generated response against the corpus chunks
and the user's issue to verify its accuracy, grounding, and tone.
"""

import logging
from typing import Dict, List, Tuple
from prompts import SYSTEM_PROMPT

logger = logging.getLogger(__name__)

DISCRIMINATOR_PROMPT = """\
You are an expert quality assurance (QA) discriminator agent. Your job is to \
cross-verify the response generated by another support agent.

TICKET DETAILS:
- Company: {company}
- Subject: {subject}
- Issue: {issue}

CORPUS EXCERPTS (The Ground Truth):
{corpus_excerpts}

GENERATED RESPONSE:
{generated_response}

EVALUATION CRITERIA:
1. STRICT GROUNDING: Is the response factually grounded in the corpus excerpts? It MUST NOT \
contain ANY hallucinated URLs, phone numbers, emails, policies, or facts not present in the excerpts.
2. ACCURACY: Does it accurately address the user's issue based solely on the provided context?
3. TONE: Is the tone appropriate (empathetic, professional, not robotic)?
4. ESCALATION CHECK: If it is an escalation, does it clearly explain why it was escalated?

INSTRUCTIONS:
Determine if the generated response meets the criteria. If it does, set "is_valid" to true.
If it contains hallucinations, contradicts the corpus, or fails to address the issue, \
set "is_valid" to false, explain the issue in "feedback", and provide a fixed \
response in "corrected_response".

Respond with a JSON object:
{{
  "is_valid": true | false,
  "feedback": "<Explain why it passed or failed>",
  "corrected_response": "<Only if is_valid is false, provide a fully corrected string response. Otherwise null.>"
}}
Do NOT include any text outside the JSON object.
"""

def evaluate_response(  # pylint: disable=too-many-arguments,too-many-locals,too-many-positional-arguments
    client, call_llm_fn, parse_json_fn, response_text: str,
    issue: str, subject: str, company: str, chunks: List[Dict]
) -> Tuple[bool, str]:
    """
    Evaluate the generated response using an LLM.
    Returns a tuple (is_valid: bool, final_response: str).
    """
    # If no response was generated, we can't evaluate it properly
    if not response_text or not response_text.strip():
        return False, "Response was empty. Escalated to a human specialist."

    corpus_context = _build_corpus_context(chunks)

    user_msg = DISCRIMINATOR_PROMPT.format(
        company=company,
        subject=subject,
        issue=issue,
        corpus_excerpts=corpus_context,
        generated_response=response_text
    )

    try:
        raw = call_llm_fn(client, SYSTEM_PROMPT, user_msg)
        parsed = parse_json_fn(raw)

        if parsed and "is_valid" in parsed:
            is_valid = parsed.get("is_valid", False)
            if is_valid:
                logger.debug("Discriminator approved the response.")
                return True, response_text

            feedback = parsed.get("feedback", "No feedback provided.")
            logger.debug("Discriminator rejected the response. Feedback: %s", feedback)
            corrected = parsed.get("corrected_response")
            if corrected and corrected.strip() and corrected.lower() != "null":
                return True, corrected
            return False, response_text
    except Exception as exc:  # pylint: disable=broad-exception-caught
        logger.warning("Discriminator LLM call failed: %s", exc)
        
    # If the discriminator fails to evaluate, we err on the side of caution
    # and return the original response
    return True, response_text

def _build_corpus_context(chunks: List[Dict]) -> str:
    """Format retrieved chunks into a readable context string."""
    if not chunks:
        return "No relevant corpus excerpts found."
    lines = []
    for i, chunk in enumerate(chunks, 1):
        topic = chunk.get("topic", "")
        topic_str = f" | topic: {topic}" if topic else ""
        lines.append(f"[Excerpt {i}] (source: {chunk.get('source', '')}{topic_str})")
        lines.append(chunk.get("text", ""))
        lines.append("")
    return "\n".join(lines)
